### ISSUE TITLE
Remove running components if one component fails

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/atomicapp#319]
In case you have f.e. 3 components and 2 start successfully and one fails you are in a weird state where you cannot run again.

This should be quite easy after #278 is merged.

**Comment by dustymabe** [comment]
So this will require us to implement for each provider. Let's itemize those here:

- [ ] Docker provider.. Documented by #421
- [ ] Kubernetes provider.. Documented by #429
- [ ] Openshift provider.. Documented by #428

**Comment by dustymabe** [comment]
@kadel do you want to take a look at #428 and #429. Maybe work with charlie on the work he is doing for #421.

Perhaps one way to do this would be to run "stop" but don't report any errors? I'm not sure.

**Comment by kadel** [comment]
@dustymabe sure, I will look into that.

**Comment by kadel** [comment]
I have been thinking about this a little bit.
One way how I would solve this is checking [here](https://github.com/projectatomic/atomicapp/blob/6b8eea7f17d9ab7cbe693a12629183c3d6dee3ca/atomicapp/nulecule/base.py#L264) if `provider.deploy()` didn't failed , either by making `deploy()` returning some value, or making sure provider always raises exception when something is wrong, and catching it here. If `deploy` fails then we would call `provider.undeploy()`.
We also have to make sure that when during undeploy, one artifact fails, provider continues to next artifacts so it tries to undeploy all artifacts.

**Comment by rtnpro** [comment]
@dustymabe isn't it already taken care by #456 ?

**Comment by dustymabe** [comment]
@kadel @rtnpro, right. The way @rtnpro implemented #456 it should take care of all of the providers. 

@rtnpro you will need to wait for #458 before we can add in the plumbing to undeploy for openshift.

**Comment by dustymabe** [comment]
ok #458 has been fixed. @rtnpro, you should be able to add the support to undeploy() in openshift now

**Comment by rtnpro** [comment]
This is fixed, already!

**Comment by dustymabe** [comment]
There a  few outstanding items in the PR: https://github.com/projectatomic/atomicapp/pull/456#issuecomment-171872694

**Comment by dustymabe** [comment]
Removing blocker label as the required change would be too risky for GA and is not worth it.
